name: Deploy Backend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: The environment to deploy to (e.g., dev, prod).
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: "${{ vars.ENVIRONMENT }}"

      - name: Install Dependencies
        run: npm install
        working-directory: backend

      - name: Deploy Backend (Lambda Functions)
        run: |
          npx serverless deploy
        working-directory: backend