name: Deploy Backend

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: "${{ vars.ENVIRONMENT }}"

      - name: Install Dependencies
        run: npm install
        working-directory: backend

      - name: Deploy Backend (Lambda Functions)
        run: |
          npx serverless deploy
        working-directory: backend