name: Deploy Frontend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: The environment to deploy to (e.g., dev, prod).

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: "${{ vars.ENVIRONMENT }}"

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Build Frontend
        run: npm run build
        working-directory: frontend

      - name: Deploy to S3
        run: aws s3 sync frontend/build s3://${{ secrets.ORG_OR_USER }}-${{ secrets.REPO }}-bucket
