name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: The environment to deploy to (e.g., dev, prod).
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - prod  

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: "${{ vars.ENVIRONMENT }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init -backend-config="key=${{ vars.ENVIRONMENT }}/terraform.tfstate"
        working-directory: infrastructure

      - name: Select Terraform Workspace
        run: terraform workspace select ${{ vars.ENVIRONMENT }} || terraform workspace new ${{ vars.ENVIRONMENT }}
        working-directory: infrastructure

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infrastructure

      - name: Terraform Apply
        run: terraform apply tfplan
        working-directory: infrastructure
